[default]
src = 'contracts/foundry-tests'
out = 'out'
libs = ['lib']
block_timestamp = 1651743369 # Arbitrary Thursday, 5 May 2022 09:36:09
verbosity = 3

# See more config options https://github.com/gakonst/foundry/tree/master/config
