name: Builder

on:
  pull_request:
  push:
    branches:
     - master

jobs:
  builder:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build Docker
      run: docker build -t "yield/ytoken-mvp:${{ github.run_id}}" -f docker/Dockerfile .
    - name: Run Builder
      run: docker run -v /output/:/srv/ytoken-mvp/output -t "yield/ytoken-mvp:${{ github.run_id }}" test
    - name: Debug
      run:  find .
    - name: Upload Buildler Log
      uses: actions/upload-artifact@v1
      with:
        name: builder-log
        path: /output/buidler.log
