name: Docker Tests

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build Docker
      run: docker build -t "yield/ytoken-mvp:${{ github.run_id}}" -f docker/Dockerfile .
    - name: Run Lint
      run: docker run -t "yield/ytoken-mvp:${{ github.run_id }}" lint
    - name: Run Builder
      run: docker run -t "yield/ytoken-mvp:${{ github.run_id }}" test
