name: ESLint

on:
  pull_request:
  push:
    branches:
     - master

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build Docker
      run: docker build -t "yield/ytoken-mvp:${{ github.run_id}}" -f docker/Dockerfile .
    - name: Run ESLint
      run: docker run -v /output/:/srv/ytoken-mvp/output -t "yield/ytoken-mvp:${{ github.run_id }}" eslint
    - name: Upload EsLint Log
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: eslint-log
        path: /output/eslint.log
